// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: flo/v1/admin.proto

package flov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListQueuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesRequest) Reset() {
	*x = ListQueuesRequest{}
	mi := &file_flo_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesRequest) ProtoMessage() {}

func (x *ListQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flo_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesRequest.ProtoReflect.Descriptor instead.
func (*ListQueuesRequest) Descriptor() ([]byte, []int) {
	return file_flo_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *ListQueuesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListQueuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []string               `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesResponse) Reset() {
	*x = ListQueuesResponse{}
	mi := &file_flo_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesResponse) ProtoMessage() {}

func (x *ListQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flo_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesResponse.ProtoReflect.Descriptor instead.
func (*ListQueuesResponse) Descriptor() ([]byte, []int) {
	return file_flo_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ListQueuesResponse) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

type ListDLQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDLQRequest) Reset() {
	*x = ListDLQRequest{}
	mi := &file_flo_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDLQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDLQRequest) ProtoMessage() {}

func (x *ListDLQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flo_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDLQRequest.ProtoReflect.Descriptor instead.
func (*ListDLQRequest) Descriptor() ([]byte, []int) {
	return file_flo_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListDLQRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListDLQRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ListDLQRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDLQResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           [][]byte               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDLQResponse) Reset() {
	*x = ListDLQResponse{}
	mi := &file_flo_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDLQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDLQResponse) ProtoMessage() {}

func (x *ListDLQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flo_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDLQResponse.ProtoReflect.Descriptor instead.
func (*ListDLQResponse) Descriptor() ([]byte, []int) {
	return file_flo_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListDLQResponse) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

type RequeueFromDLQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Ids           [][]byte               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequeueFromDLQRequest) Reset() {
	*x = RequeueFromDLQRequest{}
	mi := &file_flo_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequeueFromDLQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequeueFromDLQRequest) ProtoMessage() {}

func (x *RequeueFromDLQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flo_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequeueFromDLQRequest.ProtoReflect.Descriptor instead.
func (*RequeueFromDLQRequest) Descriptor() ([]byte, []int) {
	return file_flo_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *RequeueFromDLQRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RequeueFromDLQRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *RequeueFromDLQRequest) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

type RequeueFromDLQResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequeueFromDLQResponse) Reset() {
	*x = RequeueFromDLQResponse{}
	mi := &file_flo_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequeueFromDLQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequeueFromDLQResponse) ProtoMessage() {}

func (x *RequeueFromDLQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flo_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequeueFromDLQResponse.ProtoReflect.Descriptor instead.
func (*RequeueFromDLQResponse) Descriptor() ([]byte, []int) {
	return file_flo_v1_admin_proto_rawDescGZIP(), []int{5}
}

type TrimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	MaxAgeMs      int64                  `protobuf:"varint,3,opt,name=max_age_ms,json=maxAgeMs,proto3" json:"max_age_ms,omitempty"`
	MaxBytes      int64                  `protobuf:"varint,4,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrimRequest) Reset() {
	*x = TrimRequest{}
	mi := &file_flo_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimRequest) ProtoMessage() {}

func (x *TrimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flo_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimRequest.ProtoReflect.Descriptor instead.
func (*TrimRequest) Descriptor() ([]byte, []int) {
	return file_flo_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *TrimRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TrimRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *TrimRequest) GetMaxAgeMs() int64 {
	if x != nil {
		return x.MaxAgeMs
	}
	return 0
}

func (x *TrimRequest) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type TrimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrimResponse) Reset() {
	*x = TrimResponse{}
	mi := &file_flo_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimResponse) ProtoMessage() {}

func (x *TrimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flo_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimResponse.ProtoReflect.Descriptor instead.
func (*TrimResponse) Descriptor() ([]byte, []int) {
	return file_flo_v1_admin_proto_rawDescGZIP(), []int{7}
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_flo_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flo_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_flo_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *StatsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       map[string]string      `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_flo_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flo_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_flo_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *StatsResponse) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_flo_v1_admin_proto protoreflect.FileDescriptor

const file_flo_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x12flo/v1/admin.proto\x12\x06flo.v1\"1\n" +
	"\x11ListQueuesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\",\n" +
	"\x12ListQueuesResponse\x12\x16\n" +
	"\x06queues\x18\x01 \x03(\tR\x06queues\"Z\n" +
	"\x0eListDLQRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"#\n" +
	"\x0fListDLQResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\fR\x03ids\"]\n" +
	"\x15RequeueFromDLQRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\fR\x03ids\"\x18\n" +
	"\x16RequeueFromDLQResponse\"\x82\x01\n" +
	"\vTrimRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x1c\n" +
	"\n" +
	"max_age_ms\x18\x03 \x01(\x03R\bmaxAgeMs\x12\x1b\n" +
	"\tmax_bytes\x18\x04 \x01(\x03R\bmaxBytes\"\x0e\n" +
	"\fTrimResponse\",\n" +
	"\fStatsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"\x89\x01\n" +
	"\rStatsResponse\x12<\n" +
	"\ametrics\x18\x01 \x03(\v2\".flo.v1.StatsResponse.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc9\x02\n" +
	"\fAdminService\x12C\n" +
	"\n" +
	"ListQueues\x12\x19.flo.v1.ListQueuesRequest\x1a\x1a.flo.v1.ListQueuesResponse\x12:\n" +
	"\aListDLQ\x12\x16.flo.v1.ListDLQRequest\x1a\x17.flo.v1.ListDLQResponse\x12O\n" +
	"\x0eRequeueFromDLQ\x12\x1d.flo.v1.RequeueFromDLQRequest\x1a\x1e.flo.v1.RequeueFromDLQResponse\x121\n" +
	"\x04Trim\x12\x13.flo.v1.TrimRequest\x1a\x14.flo.v1.TrimResponse\x124\n" +
	"\x05Stats\x12\x14.flo.v1.StatsRequest\x1a\x15.flo.v1.StatsResponseB(Z&github.com/rzbill/flo-api/flo/v1;flov1b\x06proto3"

var (
	file_flo_v1_admin_proto_rawDescOnce sync.Once
	file_flo_v1_admin_proto_rawDescData []byte
)

func file_flo_v1_admin_proto_rawDescGZIP() []byte {
	file_flo_v1_admin_proto_rawDescOnce.Do(func() {
		file_flo_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flo_v1_admin_proto_rawDesc), len(file_flo_v1_admin_proto_rawDesc)))
	})
	return file_flo_v1_admin_proto_rawDescData
}

var file_flo_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_flo_v1_admin_proto_goTypes = []any{
	(*ListQueuesRequest)(nil),      // 0: flo.v1.ListQueuesRequest
	(*ListQueuesResponse)(nil),     // 1: flo.v1.ListQueuesResponse
	(*ListDLQRequest)(nil),         // 2: flo.v1.ListDLQRequest
	(*ListDLQResponse)(nil),        // 3: flo.v1.ListDLQResponse
	(*RequeueFromDLQRequest)(nil),  // 4: flo.v1.RequeueFromDLQRequest
	(*RequeueFromDLQResponse)(nil), // 5: flo.v1.RequeueFromDLQResponse
	(*TrimRequest)(nil),            // 6: flo.v1.TrimRequest
	(*TrimResponse)(nil),           // 7: flo.v1.TrimResponse
	(*StatsRequest)(nil),           // 8: flo.v1.StatsRequest
	(*StatsResponse)(nil),          // 9: flo.v1.StatsResponse
	nil,                            // 10: flo.v1.StatsResponse.MetricsEntry
}
var file_flo_v1_admin_proto_depIdxs = []int32{
	10, // 0: flo.v1.StatsResponse.metrics:type_name -> flo.v1.StatsResponse.MetricsEntry
	0,  // 1: flo.v1.AdminService.ListQueues:input_type -> flo.v1.ListQueuesRequest
	2,  // 2: flo.v1.AdminService.ListDLQ:input_type -> flo.v1.ListDLQRequest
	4,  // 3: flo.v1.AdminService.RequeueFromDLQ:input_type -> flo.v1.RequeueFromDLQRequest
	6,  // 4: flo.v1.AdminService.Trim:input_type -> flo.v1.TrimRequest
	8,  // 5: flo.v1.AdminService.Stats:input_type -> flo.v1.StatsRequest
	1,  // 6: flo.v1.AdminService.ListQueues:output_type -> flo.v1.ListQueuesResponse
	3,  // 7: flo.v1.AdminService.ListDLQ:output_type -> flo.v1.ListDLQResponse
	5,  // 8: flo.v1.AdminService.RequeueFromDLQ:output_type -> flo.v1.RequeueFromDLQResponse
	7,  // 9: flo.v1.AdminService.Trim:output_type -> flo.v1.TrimResponse
	9,  // 10: flo.v1.AdminService.Stats:output_type -> flo.v1.StatsResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_flo_v1_admin_proto_init() }
func file_flo_v1_admin_proto_init() {
	if File_flo_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flo_v1_admin_proto_rawDesc), len(file_flo_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flo_v1_admin_proto_goTypes,
		DependencyIndexes: file_flo_v1_admin_proto_depIdxs,
		MessageInfos:      file_flo_v1_admin_proto_msgTypes,
	}.Build()
	File_flo_v1_admin_proto = out.File
	file_flo_v1_admin_proto_goTypes = nil
	file_flo_v1_admin_proto_depIdxs = nil
}
