// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: flo/v1/error.proto

package flov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error model
//
// Flo uses canonical gRPC status codes for errors. REST responses map these
// to HTTP status codes. The following enum documents the expected mapping
// for API surfaces in this package. Do not rely on these values on the wire;
// they are provided for documentation and potential use in error details.
//
// Canonical mapping:
// - INVALID_ARGUMENT → 400 Bad Request
// - NOT_FOUND → 404 Not Found
// - ALREADY_EXISTS → 409 Conflict
// - DEADLINE_EXCEEDED → 504 Gateway Timeout
// - RESOURCE_EXHAUSTED → 429 Too Many Requests
// - ABORTED → 409 Conflict
// - UNAVAILABLE → 503 Service Unavailable
// - INTERNAL → 500 Internal Server Error
// - PERMISSION_DENIED → 403 Forbidden
// - UNAUTHENTICATED → 401 Unauthorized
type FloErrorCode int32

const (
	FloErrorCode_FLO_ERROR_CODE_UNSPECIFIED FloErrorCode = 0
	FloErrorCode_FLO_INVALID_ARGUMENT       FloErrorCode = 1
	FloErrorCode_FLO_NOT_FOUND              FloErrorCode = 2
	FloErrorCode_FLO_ALREADY_EXISTS         FloErrorCode = 3
	FloErrorCode_FLO_DEADLINE_EXCEEDED      FloErrorCode = 4
	FloErrorCode_FLO_RESOURCE_EXHAUSTED     FloErrorCode = 5
	FloErrorCode_FLO_ABORTED                FloErrorCode = 6
	FloErrorCode_FLO_UNAVAILABLE            FloErrorCode = 7
	FloErrorCode_FLO_INTERNAL               FloErrorCode = 8
	FloErrorCode_FLO_PERMISSION_DENIED      FloErrorCode = 9
	FloErrorCode_FLO_UNAUTHENTICATED        FloErrorCode = 10
)

// Enum value maps for FloErrorCode.
var (
	FloErrorCode_name = map[int32]string{
		0:  "FLO_ERROR_CODE_UNSPECIFIED",
		1:  "FLO_INVALID_ARGUMENT",
		2:  "FLO_NOT_FOUND",
		3:  "FLO_ALREADY_EXISTS",
		4:  "FLO_DEADLINE_EXCEEDED",
		5:  "FLO_RESOURCE_EXHAUSTED",
		6:  "FLO_ABORTED",
		7:  "FLO_UNAVAILABLE",
		8:  "FLO_INTERNAL",
		9:  "FLO_PERMISSION_DENIED",
		10: "FLO_UNAUTHENTICATED",
	}
	FloErrorCode_value = map[string]int32{
		"FLO_ERROR_CODE_UNSPECIFIED": 0,
		"FLO_INVALID_ARGUMENT":       1,
		"FLO_NOT_FOUND":              2,
		"FLO_ALREADY_EXISTS":         3,
		"FLO_DEADLINE_EXCEEDED":      4,
		"FLO_RESOURCE_EXHAUSTED":     5,
		"FLO_ABORTED":                6,
		"FLO_UNAVAILABLE":            7,
		"FLO_INTERNAL":               8,
		"FLO_PERMISSION_DENIED":      9,
		"FLO_UNAUTHENTICATED":        10,
	}
)

func (x FloErrorCode) Enum() *FloErrorCode {
	p := new(FloErrorCode)
	*p = x
	return p
}

func (x FloErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FloErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_flo_v1_error_proto_enumTypes[0].Descriptor()
}

func (FloErrorCode) Type() protoreflect.EnumType {
	return &file_flo_v1_error_proto_enumTypes[0]
}

func (x FloErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FloErrorCode.Descriptor instead.
func (FloErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_flo_v1_error_proto_rawDescGZIP(), []int{0}
}

var File_flo_v1_error_proto protoreflect.FileDescriptor

const file_flo_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x12flo/v1/error.proto\x12\x06flo.v1*\x96\x02\n" +
	"\fFloErrorCode\x12\x1e\n" +
	"\x1aFLO_ERROR_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FLO_INVALID_ARGUMENT\x10\x01\x12\x11\n" +
	"\rFLO_NOT_FOUND\x10\x02\x12\x16\n" +
	"\x12FLO_ALREADY_EXISTS\x10\x03\x12\x19\n" +
	"\x15FLO_DEADLINE_EXCEEDED\x10\x04\x12\x1a\n" +
	"\x16FLO_RESOURCE_EXHAUSTED\x10\x05\x12\x0f\n" +
	"\vFLO_ABORTED\x10\x06\x12\x13\n" +
	"\x0fFLO_UNAVAILABLE\x10\a\x12\x10\n" +
	"\fFLO_INTERNAL\x10\b\x12\x19\n" +
	"\x15FLO_PERMISSION_DENIED\x10\t\x12\x17\n" +
	"\x13FLO_UNAUTHENTICATED\x10\n" +
	"B(Z&github.com/rzbill/flo-api/flo/v1;flov1b\x06proto3"

var (
	file_flo_v1_error_proto_rawDescOnce sync.Once
	file_flo_v1_error_proto_rawDescData []byte
)

func file_flo_v1_error_proto_rawDescGZIP() []byte {
	file_flo_v1_error_proto_rawDescOnce.Do(func() {
		file_flo_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flo_v1_error_proto_rawDesc), len(file_flo_v1_error_proto_rawDesc)))
	})
	return file_flo_v1_error_proto_rawDescData
}

var file_flo_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_flo_v1_error_proto_goTypes = []any{
	(FloErrorCode)(0), // 0: flo.v1.FloErrorCode
}
var file_flo_v1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flo_v1_error_proto_init() }
func file_flo_v1_error_proto_init() {
	if File_flo_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flo_v1_error_proto_rawDesc), len(file_flo_v1_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flo_v1_error_proto_goTypes,
		DependencyIndexes: file_flo_v1_error_proto_depIdxs,
		EnumInfos:         file_flo_v1_error_proto_enumTypes,
	}.Build()
	File_flo_v1_error_proto = out.File
	file_flo_v1_error_proto_goTypes = nil
	file_flo_v1_error_proto_depIdxs = nil
}
