name: CI
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - name: Buf Lint
        run: buf lint proto
      - name: Buf Breaking (against main)
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin main:refs/remotes/origin/main || true
          buf breaking proto --against "https://github.com/${{ github.repository }}.git#branch=main,subdir=proto"


